### ISSUE TITLE
Blender manipulation to make 3d obj usable is kind of difficult to follow for non-blender users

### ISSUE THREAD

**Issue by Rakiah** [retroplasma/earth-reverse-engineering#24]
I have lot of troubles doing the manipulation described in BLENDER.MD to make the obj with the correct textures (like setting shader view to rendered and running the python script) I know this is probably linked to Blender being overly complicated but maybe the steps could be explained in a better way?

Thanks

**Comment by retroplasma** [comment]
I can add these images. Do they help?

Open script editor:
<img width="1005" alt="img" src="https://user-images.githubusercontent.com/46618410/51717769-2c9a1c00-203a-11e9-833b-20752f30a736.png">

Add hemi lamp:
<img width="1007" alt="img" src="https://user-images.githubusercontent.com/46618410/51717795-4c314480-203a-11e9-8f53-1ba1c9d0cace.png">

Viewport shading:
<img width="1007" alt="img" src="https://user-images.githubusercontent.com/46618410/51717879-9d413880-203a-11e9-98dd-954136d9a962.png">

**Comment by retroplasma** [comment]
Don't know how to do that in Blender. But I uploaded `center_scale_obj.js` just now. This node.js script centers and resizes the obj and produces model.2.obj that you can open instead of model.obj. See updated [BLENDER.md](https://github.com/retroplasma/earth-reverse-engineering/blob/master/BLENDER.md).

**Comment by Rakiah** [comment]
is working smoothly with the provided informations!
thanks
