### ISSUE TITLE
Visible octant bounds when rendering as outline/freestyle in Blender

### ISSUE THREAD

**Issue by zkg** [retroplasma/earth-reverse-engineering#51]
This might be more of a Blender related question, but maybe it relates to the way the .obj file is put together. 

My problem is that the verts do not line up from one octant to the next. This is particularly visible because I am working with outlines and freestyle, and the grid is popping up quite noticeably:

![Screenshot from 2020-04-14 13-28-30](https://user-images.githubusercontent.com/13556865/79270950-ddfdbb00-7e53-11ea-8c15-1ae1b0ff4bc6.png)

I've been trying merging by distance or even remeshing, but both alter the original shapes way too much. Any ideas on how I could mitigate this problem?

**Comment by retroplasma** [comment]
The octants should be aligned in the OBJ but the meshes are independent of one another. I think either this is messing with the outline/freestyle algorithm or perhaps it's the little vertical slopes that are hidden below the mesh on the octants' bounds, which are included in the original meshes. Maybe there's some way to configure the edge detection? Renaming this issue since it's a special case and textured rendering is working.

**Comment by retroplasma** [comment]
The octants should be aligned in the OBJ but the meshes are independent of one another. I think either this is messing with the outline/freestyle algorithm or perhaps it's the little vertical slopes that are hidden below the mesh on the octants' bounds, which are included in some of the original meshes. Maybe there's some way to configure the edge detection? Renaming this issue since it's a special case and textured rendering is working.

**Comment by retroplasma** [comment]
The octants should be aligned in the OBJ but the meshes are independent of one another. I think either this is messing with the outline/freestyle algorithm or perhaps it's the little vertical slopes that are hidden below the mesh on the octants' bounds, which are included in some of the original meshes. Maybe the edge detection can be configured somehow?

**Comment by retroplasma** [comment]
The octants should be aligned in the OBJ but the meshes are independent of one another. I think either this is messing with the outline/freestyle algorithm or perhaps it's the little vertical slopes that are hidden below the mesh on the octants' bounds, which are included in some of the original meshes. Maybe the edge detection can be configured somehow? On the protocol level I think we can't detect these slopes or do a better job at merging than Blender.

**Comment by desmondCTNG** [comment]
I found this problem too. When a house lies between two octants, it is likely that the two sides of the house are slightly different in their dimensions.

**Comment by retroplasma** [comment]
@desmondCTNG If this is about standard textured rendering that looks different than it should, please share some neighboring octant strings where that's the case, how you export them and perhaps some comparison with the original client's rendering.
