### ISSUE TITLE
coordinate system of this program

### ISSUE THREAD

**Issue by desmondCTNG** [retroplasma/earth-reverse-engineering#52]
May I ask the what coordinate system is this program using, is it WGS84? Where should I edit to get the lat long coordinates and height of every downloaded octant?

**Comment by kwea123** [comment]
The coordinate system is [ECEF](https://en.wikipedia.org/wiki/ECEF)
One example coordinate is `-3953921.4794161 ,  3345101.9590767 ,  3710332.53642205`
You can for example use library like [this](https://github.com/geospace-code/pymap3d) to convert ecef to other coordinate systems such as lla (geodetic). For example I use `ecef2enu` to convert to local coordinate system (enu) which normalizes the angle (so that the ground plane is parallel to identity rotation)

**Comment by desmondCTNG** [comment]
Thanks
