### ISSUE TITLE
Http 403 after downloading large volume data

### ISSUE THREAD

**Issue by ninglixu** [retroplasma/earth-reverse-engineering#65]
Hi there:

i was downloading an area of 0.2*0.4 degree. In the process, i got error like this. And i can;t connect to Google Earth.

Retrying https://kh.google.com/rt/earth/PlanetoidMetadata in 1 second.
Retrying https://kh.google.com/rt/earth/PlanetoidMetadata in 2 seconds.
Retrying https://kh.google.com/rt/earth/PlanetoidMetadata in 4 seconds.
Retrying https://kh.google.com/rt/earth/PlanetoidMetadata in 8 seconds.
Gave up after 5 tries.
Error: HTTP status code 403 for https://kh.google.com/rt/earth/PlanetoidMetadata

Is it becasue my computer was forbidden due to my downloading large volume data?  

Thanks

**Comment by retroplasma** [comment]
Hmm yup I guess they rate-limit after a while. Did you try again later?

> 0.2*0.4 degree

Is that around 800km² ? Do you know how far it got until it stopped? Like how many megabytes the OBJ file was or approximate area?

The program currently stops after 5 tries. That's not ideal since it doesn't resume after it gave up and exited.

Quick fix: you can change the `MAX_TRIES` number here (e.g. to `Infinity`): https://github.com/retroplasma/earth-reverse-engineering/blob/0080f5a4600e03f83dcd51ff95d4713bb9f53041/exporter/lib/get-url.js#L32

**Comment by JordanRO2** [comment]
This probably caused because of google services thinking you were attacking them (so they limited the rate), so use a VPN
